name: pyyeti
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.10
  - scipy>=0.17
  - matplotlib>=1.5
  - pandas>=0.17
  - sphinx>=1.3.1
  - ipython>=4
  - notebook>=4
  - sphinx-copybutton
  - pygments
  - pip:
    - sphinx-toggleprompt
